# Generated by Django 4.2 on 2023-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=150)),
                ('species', models.CharField(max_length=150)),
                ('tumor_site', models.CharField(max_length=150)),
                ('biosample_source', models.CharField(max_length=150)),
                ('ndonor', models.IntegerField()),
                ('nsample', models.IntegerField()),
                ('ncell', models.IntegerField()),
                ('nmalignant', models.IntegerField()),
                ('cell_sorting', models.CharField(max_length=150)),
                ('treatment', models.CharField(max_length=150)),
            ],
        ),
    ]
