# Generated by Django 4.2 on 2023-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_lrpairs_marker_celltype_marker_subcluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='study_description',
            field=models.CharField(default='Default', max_length=15000),
        ),
        migrations.AddField(
            model_name='study',
            name='study_design',
            field=models.CharField(default='Default', max_length=15000),
        ),
        migrations.AddField(
            model_name='study',
            name='study_geo',
            field=models.CharField(default='Default', max_length=150),
        ),
        migrations.AddField(
            model_name='study',
            name='study_pmid',
            field=models.CharField(default='Default', max_length=20),
        ),
        migrations.AddField(
            model_name='study',
            name='study_title',
            field=models.CharField(default='Default', max_length=1500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lrpairs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marker_celltype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marker_subcluster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signalpathway',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='singlecell',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='study',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
