# Generated by Django 4.2 on 2023-05-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_lrpairs_marker_celltype_marker_subcluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker_subcluster',
            name='avg_log2FC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker_subcluster',
            name='padj',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker_subcluster',
            name='pct1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker_subcluster',
            name='pct2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='marker_subcluster',
            name='pval',
            field=models.FloatField(),
        ),
    ]
