# Generated by Django 4.2 on 2023-06-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_study_study_description_study_study_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='study_description',
        ),
        migrations.RemoveField(
            model_name='study',
            name='study_design',
        ),
    ]
