# Generated by Django 4.2.3 on 2023-07-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_geneexpr_geneexprcorr_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexpr',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geneexprcorr',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
